TABLE_MAPPING = {
    QWATpipe: SIAleitung,
    QWAThydrant: SIAhydrant,
    QWATtank: SIAwasserbehaelter,
    # NOT MAPPED YET
    # AVAILABLE CLASSES : SIAsia405_15_lv95sia405_wasser_lk_leitung_textassoc, SIAleitung_strang_assoc, SIAsia405_15_lv95sia405_wasser_lk_leitungsknoten_textassoc, SIAleitungsknoten_knoten_assoc, SIAsia405_15_lv95sia405_wasser_lk_spezialbauwerk_textassoc, SIAsia405_15_lv95sia405_wasser_lk_spezialbauwerk_flaeche, SIAsia405_15_lv95sia405_wasser_lk_spezialbauwerk_flaecheassoc, SIAsia405_15_lv95sia405_wasser_lk_spezialbauwerk_linie, SIAsia405_15_lv95sia405_wasser_lk_spezialbauwerk_linieassoc, SIAt_ili2db_inheritance, SIAt_ili2db_settings, SIAt_ili2db_model, SIAleitung_kathodischer_schutz, SIAhausanschluss_gebaeudeanschluss, SIAleitung_verbindungsart, SIAabsperrorgan_schaltzustand, SIAleitungspunkt_lagebestimmung, SIAleitung_sanierung_erneuerung, SIAschadenstelle_ursache, SIAleitung_bettung, SIAmuffen_schubsicherung, SIAleitung_aussenbeschichtung, SIAspezialbauwerk_art, SIAhydrant_art, SIAanlage_art, SIAleitung_innenbeschichtung, SIAleitung_verlegeart, SIAstatuswerte, SIAleitung_funktion, SIAmuffen_art, SIAleitung_material, SIAspezialbauwerk_material, SIAschadenstelle_art, SIAleitung_lagebestimmung, SIAsia4055_lv95sia405_wasser_leitung_lagebestimmung, SIAsia4055_lv95sia405_wassr_lk_anlage_art, SIAhydrant_material, SIAabsperrorgan_material, SIAastatus, SIAanlage_lagebestimmung, SIAuebrige_art, SIAvalignment, SIAleitungsknoten_hoehenbestimmung, SIAhausanschluss_isolierstueck, SIAwasserbehaelter_art, SIAleitung_schubsicherung, SIAabsperrorgan_schliessrichtung, SIAwassergewinnungsanlage_art, SIAsia4055_lv95sia405_wassr_lk_leitung_funktion, SIAabsperrorgan_art, SIAleitungspunkt_hoehenbestimmung, SIArohrleitungsteil_verbindung, SIAwasserbehaelter_material, SIAleitungspunkt_art, SIAhydraulischer_knoten_knotentyp, SIAsia4055_lv95sia405_wassr_lk_spezialbauwerk_art, SIAgenauigkeit, SIAplantyp, SIAsia4055_lv95sia405_wasser_leitung_material, SIArohrleitungsteil_material, SIAleitungsknoten_lagebestimmung, SIArohrleitungsteil_art, SIAanlage_hoehenbestimmung, SIAleitung_wasserqualitaet, SIAanlage_material, SIAhalignment, SIAfoerderanlage_art, SIAabsperrorgan_schaltantrieb, SIAt_ili2db_classname, SIAt_ili2db_attrname, SIAmetaattribute, SIAabsperrorgan, SIAhydraulischer_knoten, SIAanlage, SIAfoerderanlage, SIAhausanschluss, SIAhydraulischer_strang, SIAhydrant, SIAleitungspunkt, SIAmuffen, SIArohrleitungsteil, SIAschadenstelle, SIAsia405_15_lv95sia405_wasser_lk_leitungsknoten, SIAsia405_15_lv95sia405_wasser_lk_spezialbauwerk, SIAsia405_15_lv95sia405_wasser_lk_anlage, SIAsia405_15_lv95sia405_wasser_lk_leitung, SIAspezialbauwerk, SIAuebrige, SIAwassergewinnungsanlage, SIAhydraulischer_knoten_text, SIAhydraulischer_strang_text, SIAleitung_text, SIAleitungsknoten_text, SIAspezialbauwerk_flaeche, SIAspezialbauwerk_linie, SIAspezialbauwerk_text, SIAuebersichtsplanposition, SIAsia405_15_lv95sia405_wasser_lk_leitung_text, SIAsia405_15_lv95sia405_wasser_lk_leitungsknoten_text, SIAsia405_15_lv95sia405_wasser_lk_spezialbauwerk_text, SIAt_ili2db_dataset, SIAt_ili2db_basket
    # QWAThydrant_material: REPLACE_ME,
    # QWAThydrant_model_inf: REPLACE_ME,
    # QWAThydrant_model_sup: REPLACE_ME,
    # QWAThydrant_output: REPLACE_ME,
    # QWAThydrant_provider: REPLACE_ME,
    # QWATnetwork_element: REPLACE_ME,
    # QWATdistributor: REPLACE_ME,
    # QWATfolder: REPLACE_ME,
    # QWATobject_reference: REPLACE_ME,
    # QWATprecision: REPLACE_ME,
    # QWATprecisionalti: REPLACE_ME,
    # QWATstatus: REPLACE_ME,
    # QWATnode: REPLACE_ME,
    # QWATdistrict: REPLACE_ME,
    # QWATvisible: REPLACE_ME,
    # QWATpressurezone: REPLACE_ME,
    # QWATconsumptionzone: REPLACE_ME,
    # QWATdamage: REPLACE_ME,
    # QWATcover: REPLACE_ME,
    # QWATinstallation: REPLACE_ME,
    # QWATremote_type: REPLACE_ME,
    # QWATwatertype: REPLACE_ME,
    # QWATcover_type: REPLACE_ME,
    # QWATcrossing: REPLACE_ME,
    # QWATleak: REPLACE_ME,
    # QWATleak_cause: REPLACE_ME,
    # QWATchamber: REPLACE_ME,
    # QWATpart: REPLACE_ME,
    # QWATpart_type: REPLACE_ME,
    # QWATmeter: REPLACE_ME,
    # QWATbedding: REPLACE_ME,
    # QWATpipe_function: REPLACE_ME,
    # QWATpipe_installmethod: REPLACE_ME,
    # QWATpipe_material: REPLACE_ME,
    # QWATpipe_protection: REPLACE_ME,
    # QWATprotectionzone: REPLACE_ME,
    # QWATprotectionzone_type: REPLACE_ME,
    # QWATremote: REPLACE_ME,
    # QWATprintmap: REPLACE_ME,
    # QWATmeter_reference: REPLACE_ME,
    # QWATpressurecontrol_type: REPLACE_ME,
    # QWATpump: REPLACE_ME,
    # QWATpump_operating: REPLACE_ME,
    # QWATpump_type: REPLACE_ME,
    # QWATsamplingpoint: REPLACE_ME,
    # QWATsource: REPLACE_ME,
    # QWATsource_quality: REPLACE_ME,
    # QWATsource_type: REPLACE_ME,
    # QWATsubscriber: REPLACE_ME,
    # QWATsubscriber_type: REPLACE_ME,
    # QWATsubscriber_reference: REPLACE_ME,
    # QWATcistern: REPLACE_ME,
    # QWAToverflow: REPLACE_ME,
    # QWATtank_firestorage: REPLACE_ME,
    # QWATtreatment: REPLACE_ME,
    # QWATsurveypoint: REPLACE_ME,
    # QWATsurvey_type: REPLACE_ME,
    # QWATworker: REPLACE_ME,
    # QWATvalve: REPLACE_ME,
    # QWATvalve_function: REPLACE_ME,
    # QWATnominal_diameter: REPLACE_ME,
    # QWATvalve_type: REPLACE_ME,
    # QWATvalve_actuation: REPLACE_ME,
}

