name: Interlis-tests

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  interlis-tests:
    name: Interlis-tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install python deps
        run: pip install -r qgepplugin/interlis/requirements.txt

      - name: Run tests
        run: |
          cd qgepplugin
          python -m unittest interlis.tests
