name: Interlis-tests

on:
  push:
    branches:
      - master
      - dev-interlisexport
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - dev-interlisexport

jobs:
  interlis-tests:
    name: Interlis-tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install python deps
        run: pip install -r qgepplugin/interlis/requirements.txt

      - name: Run tests
        run: |
          cd qgepplugin
          python -m unittest interlis.tests
        env:
            PGHOST: 127.0.0.1
            PGPORT: 5432
            PGDATABASE: qgep_prod
            PGUSER: postgres
            PGPASS: postgres
